version: '3'
services:
  builder:
    container_name: ngx-esy-jsonapi
    image: ubuntu24.04-node-22-ngx-esy-jsonapi
    network_mode: 'host'
    volumes:
      - .:/home/ubuntu/ngx-esy-jsonapi
    stdin_open: true
    tty: true
    env_file:
      - .env
